Repository pyrevitlabs/pyRevit, pull requests merged in 2023-06, with the labels that each got.

#1837 Fix 2d toggle reload behaviour
  extensions/pyRevitTools.extension/pyRevit.tab/Toggles.panel/toggles3.stack/Override 2D.smartbutton/script.py
Labels: Tools

#1799 Russian localization Settings Window
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/About.pushbutton/AboutWindow.ResourceDictionary.en_us.xaml
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/About.pushbutton/AboutWindow.ResourceDictionary.ru.xaml
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/About.pushbutton/AboutWindow.xaml
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/About.pushbutton/aboutscript.py
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/Settings.smartbutton/SettingsWindow.ResourceDictionary.en_us.xaml
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/Settings.smartbutton/SettingsWindow.ResourceDictionary.ru.xaml
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/Settings.smartbutton/SettingsWindow.xaml
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/Settings.smartbutton/script.py
Labels: Prioritize, Localization

#1777 fix assembly cache
  pyrevitlib/pyrevit/runtime/InvokableDLLEngine.cs
Labels: Prioritize, Bundles

#1841 added possibility for multiple selection
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit1.stack/Match.splitpushbutton/Match.pushbutton/script.py
Labels: Enhancement, Tools

#1842 Feature/1815
  extensions/pyRevitTools.extension/pyRevit.tab/Project.panel/Wipe.pulldown/Wipe All Project Parameters.pushbutton/script.py
  extensions/pyRevitTools.extension/pyRevit.tab/Project.panel/Wipe.pulldown/bundle.yaml
Labels: Enhancement

#1849 Settings translated in french
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/Settings.smartbutton/SettingsWindow.ResourceDictionary.fr_fr.xaml
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/Settings.smartbutton/bundle.yaml
Labels: Tools, Localization

#1852 Issue #1840
  pyrevitlib/pyrevit/forms/__init__.py
Labels: Bug
