Repository pyrevitlabs/pyRevit, pull requests merged in 2023-03, with the labels that each got.

#1747 Fix: other.rfa Content Button Bundle Marker #1745
  pyrevitlib/pyrevit/extensions/components.py
Labels: Bug, Enhancement, Bundles

#1753 New Feature override 2D elements in current view
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit3.stack/Override.pulldown/Override 2D.smartbutton/bundle.yaml
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit3.stack/Override.pulldown/Override 2D.smartbutton/icon.png
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit3.stack/Override.pulldown/Override 2D.smartbutton/off.png
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit3.stack/Override.pulldown/Override 2D.smartbutton/on.png
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit3.stack/Override.pulldown/Override 2D.smartbutton/script.py
Labels: New Feature

#1752 Select Elements from Group and Subgroups
  extensions/pyRevitTools.extension/pyRevit.tab/Selection.panel/select.stack/Select.pulldown/Select Group and Subgroup Elements.pushbutton/bundle.yaml
  extensions/pyRevitTools.extension/pyRevit.tab/Selection.panel/select.stack/Select.pulldown/Select Group and Subgroup Elements.pushbutton/icon.png
  extensions/pyRevitTools.extension/pyRevit.tab/Selection.panel/select.stack/Select.pulldown/Select Group and Subgroup Elements.pushbutton/script.py
Labels: New Feature

#1774 improved the 2D elements highlighter
  extensions/pyRevitTools.extension/pyRevit.tab/Toggles.panel/toggles3.stack/Override 2D.smartbutton/script.py
Labels: Enhancement, Tools

#1728 Added additional configuration options for numberSlider per issue #1720
  pyrevitlib/pyrevit/forms/__init__.py
Labels: Enhancement

#1709 fix: add generic itrerable support to make_link
  pyrevitlib/pyrevit/output/linkmaker.py
Labels: Enhancement, Tools
