Repository pyrevitlabs/pyRevit, pull requests merged in 2024-10, with the labels that each got.

#2422 IronPython 3 Compatibility and Update for xlrd & xlsxwriter
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/Settings.smartbutton/script.py
  pyrevitlib/pyrevit/__init__.py
  pyrevitlib/pyrevit/compat.py
  pyrevitlib/pyrevit/extensions/genericcomps.py
  pyrevitlib/pyrevit/forms/__init__.py
  pyrevitlib/pyrevit/framework.py
  pyrevitlib/pyrevit/loader/asmmaker.py
  pyrevitlib/pyrevit/routes/server/base.py
  pyrevitlib/pyrevit/runtime/types.py
  site-packages/xlrd/examples/namesdemo.xls
  site-packages/xlrd/examples/xlrdnameAPIdemo.py
  site-packages/xlrd/xlsx.py
  site-packages/xlsxwriter/__init__.py
  site-packages/xlsxwriter/app.py
  site-packages/xlsxwriter/chart.py
  site-packages/xlsxwriter/chart_area.py
  site-packages/xlsxwriter/chart_bar.py
  site-packages/xlsxwriter/chart_column.py
  site-packages/xlsxwriter/chart_doughnut.py
  site-packages/xlsxwriter/chart_line.py
  site-packages/xlsxwriter/chart_pie.py
  site-packages/xlsxwriter/chart_radar.py
  site-packages/xlsxwriter/chart_scatter.py
  site-packages/xlsxwriter/chart_stock.py
  site-packages/xlsxwriter/chartsheet.py
  site-packages/xlsxwriter/comments.py
  site-packages/xlsxwriter/compat_collections.py
  site-packages/xlsxwriter/compatibility.py
  site-packages/xlsxwriter/contenttypes.py
  site-packages/xlsxwriter/core.py
  site-packages/xlsxwriter/custom.py
  site-packages/xlsxwriter/drawing.py
  site-packages/xlsxwriter/exceptions.py
  site-packages/xlsxwriter/format.py
  site-packages/xlsxwriter/metadata.py
  site-packages/xlsxwriter/packager.py
  site-packages/xlsxwriter/relationships.py
  site-packages/xlsxwriter/shape.py
  site-packages/xlsxwriter/sharedstrings.py
  site-packages/xlsxwriter/styles.py
  site-packages/xlsxwriter/table.py
  site-packages/xlsxwriter/theme.py
  site-packages/xlsxwriter/utility.py
  site-packages/xlsxwriter/vml.py
  site-packages/xlsxwriter/workbook.py
  site-packages/xlsxwriter/worksheet.py
  site-packages/xlsxwriter/xmlwriter.py
Labels: Enhancement, Python 3, IronPython, Highlight, dependencies

#2427 Loader refactor
  dev/pyRevitLabs/pyRevitLabs.TargetApps.Revit/RevitProduct.cs
  pyrevitlib/pyrevit/extensions/extensionmgr.py
  pyrevitlib/pyrevit/loader/sessionmgr.py
  pyrevitlib/pyrevit/script.py
Labels: Command Line Utility (CLI), Runtime

#2425 Update radar_check.py - Code Cleanup, expanding tabulated info
  extensions/pyRevitTools.extension/checks/radar_check.py
Labels: Extension Checks

#2430 Update __init__.py
  pyrevitlib/pyrevit/coreutils/__init__.py
Labels: Bug, Extensions

#2428 CRITICAL [pyrevit.runtime] Can not find required reference assembly: System.Drawing.Common
  pyrevitlib/pyrevit/runtime/__init__.py
Labels: Bug, Runtime, pyRevit 5
