Repository pyrevitlabs/pyRevit, pull requests merged in 2025-09, with the labels that each got.

#2819 Fix for #2818 ensure
  pyrevitlib/pyrevit/revit/db/ensure.py
Labels: API Change

#2812 Update pyrevitlib\rpws\server.py
  pyrevitlib/rpws/server.py
Labels: Tools

#2820 add unit, storagetype to select parameters dialogue
  pyrevitlib/pyrevit/forms/ParameterItemStyle.xaml
  pyrevitlib/pyrevit/forms/__init__.py
Labels: API Change

#2824 Adding Revitesse to extensions
  extensions/extensions.json
Labels: Extensions
