Repository pyrevitlabs/pyRevit, pull requests merged in 2025-02, with the labels that each got.

#2556 tool: Full audit, fix views count
  extensions/pyRevitTools.extension/checks/audit_all_check.py
  pyrevitlib/pyrevit/revit/db/count.py
Labels: Tools

#2562 performance: SelectFromList on large list
  pyrevitlib/pyrevit/forms/SelectFromList.xaml
Labels: Enhancement

#2585 fix: get_rvt_link_doc_name in query.py
  pyrevitlib/pyrevit/revit/db/query.py
Labels: Bug, Tools

#2586 doc: tooltip improvement for Select Element Types Tool / Search
  extensions/pyRevitCore.extension/pyRevit.tab/pyRevit.panel/tools.stack/Search.pushbutton/bundle.yaml
  extensions/pyRevitTools.extension/pyRevit.tab/Selection.panel/select.stack/Select.pulldown/Select Element Types.pushbutton/bundle.yaml
Labels: Tools

#2579 fix: CLI, removed exception from ClearAllCaches
  dev/pyRevitLabs/pyRevitLabs.PyRevit/PyRevitCaches.cs
Labels: Bug, Command Line Utility (CLI)
