Repository pyrevitlabs/pyRevit, pull requests merged in 2025-06, with the labels that each got.

#2691 Color Splasher : Wrong Revit API Class invocation
  extensions/pyRevitTools.extension/pyRevit.tab/Analysis.panel/ColorSplasher.pushbutton/script.py
Labels: Tools

#2702 Add support for 'title:' in the .panel bundle.yaml
  pyrevitlib/pyrevit/loader/uimaker.py
Labels: Bundles

#2707 Missing icons
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit1.stack/Match.splitpushbutton/icon.dark.png
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit1.stack/Match.splitpushbutton/icon.png
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit1.stack/Patterns.splitpushbutton/icon.dark.png
  extensions/pyRevitTools.extension/pyRevit.tab/Modify.panel/edit1.stack/Patterns.splitpushbutton/icon.png
Labels: Enhancement
