Repository pyrevitlabs/pyRevit, pull requests merged in 2025-04, with the labels that each got.

#2636 Fix/2633 - Callable Import Error
  pyrevitlib/pyrevit/compat.py
  pyrevitlib/pyrevit/coreutils/pyutils.py
Labels: Misc Compatibility

#2641 Switch for .net core Desktop connector API
  pyrevitlib/pyrevit/interop/adc.py
Labels: Bug

#2640 Adding exitscript option to SelectFromList from pyrevit.forms
  pyrevitlib/pyrevit/forms/__init__.py
Labels: Enhancement

#2651 fixes commit f81f483 + formatting
  pyrevitlib/pyrevit/forms/__init__.py
Labels: Bug

#2652 typo in forms init.py file
  pyrevitlib/pyrevit/forms/__init__.py
Labels: Bug

#2657 Adding hosted level and z-offset from level to list DWGs printout
  extensions/pyRevitTools.extension/pyRevit.tab/Project.panel/ptools.stack/Links.pulldown/ListDWGs.pushbutton/ListDWGs_script.py
Labels: Enhancement
